const fetch = (...args) => import('node-fetch').then(({default: fetch}) => fetch(...args));

async function seed() {
  const baseUrl = 'http://localhost:5001/api';
  const ownerLoginId = 'ROOMHY9999';

  console.log("Seeding data to API...");

  const fetchApi = async (url, method, body) => {
    const res = await fetch(url, {
      method,
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body)
    });
    const data = await res.json().catch(() => null);
    if (!res.ok) {
      console.error(`Failed ${method} ${url}:`, data);
      throw new Error("API Error");
    }
    return data;
  };

  try {
    // Get Properties First
    const propRes = await fetch(`${baseUrl}/properties/owner/${ownerLoginId}`);
    const propData = await propRes.json();
    const properties = propData.properties || [];
    let propertyId = null;
    
    if (properties.length > 0) {
      propertyId = properties[0]._id;
    } else {
      console.log("Creating dummy property...");
      const newProp = await fetchApi(`${baseUrl}/properties`, 'POST', {
        ownerLoginId,
        title: "Premium PG For Testing",
        propertyType: "PG",
        city: "Delhi"
      });
      propertyId = newProp.property?._id;
    }

    // 1. 10-Month Tenant
    const date10 = new Date();
    date10.setMonth(date10.getMonth() - 10);
    await fetchApi(`${baseUrl}/tenants`, 'POST', {
      name: "Aryan (10-Month Tester)",
      phone: `888${Math.floor(1000000 + Math.random() * 9000000)}`,
      roomNo: "101",
      status: "active",
      ownerLoginId,
      property: propertyId,
      moveInDate: date10.toISOString(),
      agreementSignedAt: date10.toISOString()
    });
    console.log("Added 10-month tenant");

    // 2. 11-Month Tenant
    const date11 = new Date();
    date11.setMonth(date11.getMonth() - 11);
    await fetchApi(`${baseUrl}/tenants`, 'POST', {
      name: "Vikram (11-Month Tester)",
      phone: `888${Math.floor(1000000 + Math.random() * 9000000)}`,
      roomNo: "102",
      status: "active",
      ownerLoginId,
      property: propertyId,
      moveInDate: date11.toISOString(),
      agreementSignedAt: date11.toISOString()
    });
    console.log("Added 11-month tenant");

    // 3. Leads (Booking Request)
    await fetchApi(`${baseUrl}/bookings`, 'POST', {
      ownerLoginId,
      propertyId,
      name: "Rahul Verma (Test Lead)",
      phone: "9876543210",
      email: "rahul.test@example.com",
      status: "pending",
      notes: "Generated by system test"
    });
    console.log("Added Test Lead");

    // 4. Rent (Accounting)
    // Needs tenantId, which we might not easily have unless we fetch tenants first
    const tenantsRes = await fetch(`${baseUrl}/tenants/owner/${ownerLoginId}`);
    const tenantsData = await tenantsRes.json();
    const activeTenant = tenantsData.tenants?.find(t => t.status === 'active');
    
    if (activeTenant) {
      await fetchApi(`${baseUrl}/rent`, 'POST', {
        ownerLoginId,
        tenantId: activeTenant._id,
        propertyId: activeTenant.property?._id || activeTenant.property,
        tenantName: activeTenant.name,
        roomNumber: activeTenant.roomNo || "101",
        collectionMonth: new Date().toISOString().slice(0, 7),
        rentAmount: 8500,
        totalDue: 8500,
        paymentStatus: 'pending',
        dueDate: new Date(new Date().getFullYear(), new Date().getMonth(), 15).toISOString()
      });
      console.log("Added Rent Record");

      // 5. Complaint
      await fetchApi(`${baseUrl}/complaints`, 'POST', {
        ownerLoginId,
        tenantId: activeTenant._id,
        tenantName: activeTenant.name,
        propertyId: activeTenant.property?._id || activeTenant.property,
        category: "Plumbing",
        description: "Tap is leaking in the washroom (Test)",
        priority: "High",
        status: "pending"
      });
      console.log("Added Complaint");
    }

    // 6. Staff
    await fetchApi(`${baseUrl}/employees`, 'POST', {
      name: "Amit Kumar (Test Staff)",
      loginId: `amit_${Math.floor(Math.random()*1000)}`,
      phone: `99${Math.floor(10000000 + Math.random() * 90000000)}`,
      role: "Warden",
      parentLoginId: ownerLoginId,
      isActive: true
    });
    console.log("Added Staff");

    // 7. Add Electricity Reading
    const roomsRes = await fetch(`${baseUrl}/rooms/owner/${ownerLoginId}`);
    const roomsData = await roomsRes.json();
    const rooms = roomsData.rooms || [];
    
    if (rooms.length > 0) {
      const room = rooms[0];
      await fetchApi(`${baseUrl}/rooms/${room._id}/readings`, 'POST', {
        unitCost: 8.5,
        initialReading: 1200,
        initialReadingDate: new Date(new Date().setDate(new Date().getDate() - 30)).toISOString(),
        finalReading: 1350,
        finalReadingDate: new Date().toISOString(),
        description: "May Electricity Bill"
      });
      console.log("Added Electricity Reading to Room", room.number || room.roomNo);
    } else {
      console.log("No rooms found to add electricity reading. Creating a dummy property and room...");
      const newProp = await fetchApi(`${baseUrl}/properties`, 'POST', {
        ownerLoginId,
        title: "Premium PG For Testing",
        propertyType: "PG",
        city: "Delhi"
      });
      
      const newRoom = await fetchApi(`${baseUrl}/rooms`, 'POST', {
        propertyId: newProp.property?._id,
        ownerLoginId,
        roomNo: "101",
        rent: 8500,
        electricityUnitCost: 8.5
      });
      
      await fetchApi(`${baseUrl}/rooms/${newRoom.room?._id}/readings`, 'POST', {
        unitCost: 8.5,
        initialReading: 1200,
        initialReadingDate: new Date(new Date().setDate(new Date().getDate() - 30)).toISOString(),
        finalReading: 1350,
        finalReadingDate: new Date().toISOString(),
        description: "May Electricity Bill"
      });
      console.log("Added Room and Electricity Reading");
    }

    console.log("Seeding complete!");

  } catch (err) {
    console.error("Seeding failed:", err);
  }
}

seed();
