const mongoose = require('mongoose');
const dotenv = require('dotenv');
const path = require('path');

dotenv.config({ path: path.join(__dirname, '.env') });

const Tenant = require('./models/Tenant');
const Complaint = require('./models/Complaint');
const VisitorLog = require('./models/VisitorLog');
const TenantLeaveRequest = require('./models/TenantLeaveRequest');
const LedgerEntry = require('./models/LedgerEntry');
const Employee = require('./models/Employee');
const StaffAttendance = require('./models/StaffAttendance');
const BookingRequest = require('./models/BookingRequest');
const Rent = require('./models/Rent');

async function runTests() {
  try {
    await mongoose.connect(process.env.MONGO_URI, { useNewUrlParser: true, useUnifiedTopology: true });
    console.log("Connected to MongoDB.");

    // 1. Find a baseline Tenant
    let tenant = await Tenant.findOne({ status: 'active' }).sort({ createdAt: -1 }).populate('property');
    if (!tenant) {
      console.log("No tenant found! Please add a tenant first.");
      process.exit(1);
    }
    const ownerLoginId = tenant.ownerLoginId || 'SYSTEM';
    const propertyId = tenant.property ? tenant.property._id : null;
    
    console.log(`[MODULE 1: TENANTS] Using active tenant: ${tenant.name}`);

    // Create 10-month tenant
    const date10MonthsAgo = new Date();
    date10MonthsAgo.setMonth(date10MonthsAgo.getMonth() - 10);
    const tenant10 = new Tenant({
      name: "Aryan (10-Month Tester)",
      phone: "8888888881",
      property: propertyId,
      roomNo: "101",
      status: "active",
      ownerLoginId: ownerLoginId,
      moveInDate: date10MonthsAgo,
      agreementSignedAt: date10MonthsAgo
    });
    await tenant10.save();
    console.log(`[MODULE 1] Added tenant expiring in 1 month (10 months old)`);

    // Create 11-month tenant
    const date11MonthsAgo = new Date();
    date11MonthsAgo.setMonth(date11MonthsAgo.getMonth() - 11);
    const tenant11 = new Tenant({
      name: "Vikram (11-Month Tester)",
      phone: "8888888882",
      property: propertyId,
      roomNo: "102",
      status: "active",
      ownerLoginId: ownerLoginId,
      moveInDate: date11MonthsAgo,
      agreementSignedAt: date11MonthsAgo
    });
    await tenant11.save();
    console.log(`[MODULE 1] Added tenant expired today (11 months old)`);

    // 2. Leads & Bookings
    const booking = new BookingRequest({
      propertyId: propertyId,
      ownerLoginId: ownerLoginId,
      name: "Rahul Verma (Test Lead)",
      phone: "9876543210",
      email: "rahul.test@example.com",
      status: "pending",
      notes: "Generated by system test"
    });
    await booking.save();
    console.log(`[MODULE 2: LEADS] Inserted test lead`);

    // 3. Accounting (Ledger & Rent)
    const ledger = new LedgerEntry({
      ownerLoginId: ownerLoginId,
      tenantId: tenant._id,
      propertyId: propertyId,
      type: "charge",
      amount: 5000,
      description: "Monthly Rent (Test)",
      date: new Date()
    });
    await ledger.save();
    
    const currentMonth = new Date().toISOString().slice(0, 7);
    const rent = new Rent({
      ownerLoginId: ownerLoginId,
      tenantId: tenant._id,
      propertyId: propertyId,
      tenantName: tenant.name,
      roomNumber: tenant.roomNo || "101",
      collectionMonth: currentMonth,
      rentAmount: 8500,
      totalDue: 8500,
      paymentStatus: 'pending',
      dueDate: new Date(new Date().getFullYear(), new Date().getMonth(), 15)
    });
    await rent.save();
    console.log(`[MODULE 3: ACCOUNTING/RENT] Inserted Rent & Ledger entries`);

    // 4. Complaints
    const complaint = new Complaint({
      ownerLoginId: ownerLoginId,
      tenantId: tenant._id,
      tenantName: tenant.name,
      propertyId: propertyId,
      category: "Plumbing",
      description: "Tap is leaking in the washroom (Test)",
      priority: "High",
      status: "pending"
    });
    await complaint.save();
    console.log(`[MODULE 4: COMPLAINTS] Inserted Plumbing complaint`);

    // 5. Staff
    const staff = new Employee({
      name: "Amit Kumar (Test Staff)",
      loginId: `amit_${Math.floor(Math.random()*1000)}`,
      phone: `99${Math.floor(10000000 + Math.random() * 90000000)}`,
      role: "Warden",
      parentLoginId: ownerLoginId,
      isActive: true
    });
    await staff.save();
    console.log(`[MODULE 5: STAFF] Inserted Test Staff`);

    // 6. Attendance & Entry (Staff Attendance)
    const staffAtt = new StaffAttendance({
      employeeId: staff._id,
      ownerLoginId: ownerLoginId,
      date: new Date(),
      status: "Present",
      checkIn: "09:00 AM"
    });
    await staffAtt.save();
    console.log(`[MODULE 6: STAFF ATTENDANCE] Inserted check-in`);

    // 7. Gate & Visitor (Tenant Pass)
    const visitor = new VisitorLog({
      ownerLoginId: ownerLoginId,
      name: "Suresh (Guest)",
      phone: "9123456789",
      hostName: tenant.name,
      hostRoom: tenant.roomNo || '-',
      purpose: "Meeting",
      status: "Pre-approved",
      entryTime: null
    });
    await visitor.save();
    console.log(`[MODULE 7: GATE/VISITORS] Inserted Visitor Pass`);

    // 8. Leave Requests
    const leave = new TenantLeaveRequest({
      ownerLoginId: ownerLoginId,
      tenantId: tenant._id,
      tenantName: tenant.name,
      roomNo: tenant.roomNo || '-',
      fromDate: new Date().toISOString(),
      toDate: new Date(Date.now() + 86400000*3).toISOString(),
      reason: "Going home for festival (Test)",
      status: 'Pending'
    });
    await leave.save();
    console.log(`[MODULE 8: LEAVES] Inserted Leave Request`);

    console.log("--- TEST DATA INJECTION COMPLETE ---");
    process.exit(0);
  } catch (err) {
    console.error("Error:", err);
    process.exit(1);
  }
}

runTests();
